title: Zhenghao Fei
description: Agricultural robotics researcher
markdown: kramdown
exclude:
  - README.md
  - _drafts/

defaults:
  - scope:
      type: posts
    values:
      layout: post
      permalink: /blog/:title/
